coverage:
  precision: 2
  round: down
  range: "85...100"
  status:
    project:
      default:
        target: 85%
        threshold: 0%
        base: auto
        if_not_found: failure
        if_ci_failed: error
        informational: false
        only_pulls: false
    patch: off
