# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/asecurityteam/rolling"
  version = "^1.0.0"

[[constraint]]
  name = "github.com/shirou/gopsutil"
  version = "2.19.1"

[prune]
  go-tests = true
  unused-packages = true
